spring.application.name=Caffeine Assignment
spring.mongodb.uri=mongodb+srv://user:user@cluster0.qapl5qb.mongodb.net/caffeineDb?appName=Cluster0
spring.mongodb.database=caffeineDb

server.port=9090
server.address=0.0.0.0
management.endpoint.health.enabled=false
